# **Brief Introduction to Numpy**

In [70]:
#import numpy 
import numpy as np

## **Array in NumPy**

- Slicing in Numpy
- Modifying an array in NumPy 

In [71]:
#Creating an Array using Numpy
a = np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [72]:
# Normal Array
b = [1,2,3,4,5]
type(b)

list

## **Slicing : Normal Array vs NumPy Array**

In [73]:
# Slice NumPy Array
a[1:3]

array([2, 3])

In [74]:
# Slice Normal Array
b[1:3]

[2, 3]

In [75]:
#Assigning value to a slice in NumPy 
a[1:3] = 7
a

array([1, 7, 7, 4, 5])

In [76]:
# Can't Assign value to Slice (throws an error)
b[1:3] = 8
b

TypeError: can only assign an iterable

## **Modifying an array in Numpy**
- Assigning a numpy array to another variable creates another instance of the same array.
- Modifying an instance would modify all other instances.
- To create a copy of an array use 'copy' function.

In [ ]:
# Assign array to a new variable
a = np.array([1,2,3,4,5])
d = a
print(d)

#Modifying 'd'  would modify 'a' as well 
d[1] = 9
print(d)
print(a)

[1 2 3 4 5]
[1 9 3 4 5]
[1 9 3 4 5]


In [ ]:
# Copying Numpy Array
c = np.copy(a)
print(c)

#Change 3rd elemnt to 5
c[2] = 5
print(c)

#Modifying 'c' does not affect 'a'
print(a)

[1 9 3 4 5]
[1 9 5 4 5]
[1 9 3 4 5]


## **Reshaping an Array**
- Use reshape function
- By reshaping we can add or remove dimensions or change number of elements in each dimension.
- `ndim` : Returns dimension of the array



In [ ]:
#1D to 2D

#Array a with 10 elements
a = np.array([1,2,3,4,5,6,7,8,9,0])


#Reshape a to a 2D array
b = a.reshape(2,5)

print("Array a :", a)
#Array dimension 
print("Dimension : ",a.ndim)
print("Array b :", b)
#Array dimension 
print("Dimension :",b.ndim)



Array a : [1 2 3 4 5 6 7 8 9 0]
Dimension :  1
Array b : [[1 2 3 4 5]
 [6 7 8 9 0]]
Dimension : 2


## **Random Numbers in Numpy**
- Import `random` module from NumPy
- `randint(x)` generates random integer value from 0 to x
-  `randint(x,size(dimension))` generates random array of specified dimension
-  The `choice()` method allows you to generate a random value based on an array of values.

In [ ]:
# Import random module

from numpy import random as rd

#Generate a random integer from 0 to 100
rd.randint(100)

81

In [ ]:
#Generate a 1-D array containing 7 random integers
rd.randint(100,size=7)

array([59,  5, 64, 75, 67, 65, 87])

In [ ]:
#Generate a 2-D array with 3 rows, each row containing 6 random integers
rd.randint(50,size=(3,6))

array([[14, 20, 23, 30,  1, 24],
       [12,  5, 46, 28, 22, 15],
       [10,  1, 27, 31,  4, 40]])

In [ ]:
#Select a random value from the array
print(rd.choice([1,2,3,4,5]))

#Select a random value from the array and store it in another array
print(rd.choice([1,2,3,4,5],size=(2,3)))

4
[[4 3 5]
 [3 2 4]]
